# Generated by Django 2.2.1 on 2021-02-13 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210119_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 23, 52, 46, 351301)),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Order'),
        ),
    ]
