# Generated by Django 3.1.3 on 2020-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rows',
            field=models.ManyToManyField(through='market.OrderRow', to='market.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حال خرید'), (2, 'ثبت\u200cشده'), (3, 'لغوشده'), (4, 'ارسال\u200cشده')], default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=20000),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
