# Generated by Django 2.2.1 on 2020-12-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20201129_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rows',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='market.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
